version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
      POSTGRES_HOST: db
    ports:
      - "5437:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat_net

  redis:
    image: redis:alpine
    networks:
      - chat_net

  app:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8100:8000"
    depends_on:
      - db
      - redis
    networks:
      - chat_net

networks:
  chat_net:
    driver: bridge

volumes:
  postgres_data:
