version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d chat_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    networks:
      - chat_net

  app:
    build: .
    command: sh -c "sleep 10 && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    # command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8100:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - chat_net
    environment:
      - POSTGRES_DB=chat_db
networks:
  chat_net:
    driver: bridge

volumes:
  postgres_data:
